Post teams endpoint
luuk-royal/tapawingohike_backend pull request #12
Opened 2024-06-03 09:24 UTC by hostadvantage

2024-06-03 10:46 UTC, luuk-royal requested changes

2024-06-03 10:46 UTC, luuk-royal commented on Tapawingo_backend/Controllers/TeamsController.cs
> +                return team != null ? Ok(team) : BadRequest("Error creating team");
try catch en specifieke error gooien gebaseerd op wat fout gaat.

2024-06-03 10:46 UTC, luuk-royal commented on Tapawingo_backend/Interface/ITeamRepository.cs
> +        Task<Team> AddTeam(CreateTeamDto team);
Moet CreateTeam zijn, Add wordt gebruikt om bijv. een team aan een editie toe te voegen. Bijv. AddTeamToEdition

2024-06-05 08:49 UTC, MegaMaster01 requested changes
Nog geen testen aanwezig voor deze endpoint

2024-06-10 07:26 UTC, VincentVel submitted a review, later dismissed
is goed

2024-06-10 07:27 UTC, VincentVel submitted a review, later dismissed
is goed

2024-06-10 14:03 UTC, luuk-royal requested changes

2024-06-10 14:03 UTC, luuk-royal commented on Tapawingo_backend/Services/TeamService.cs
> +            return _mapper.Map<CreateTeamDto>(_teamRepository.CreateTeam(model));
Dit moet toch via de mapper van model naar team gemapt worden?

2024-06-11 09:03 UTC, hostadvantage commented on Tapawingo_backend/Services/TeamService.cs
> +            return _mapper.Map<CreateTeamDto>(_teamRepository.CreateTeam(model));
Nee je krijgt een Team object van de repo en geeft terug een TeamDTO dus andersom

2024-06-11 09:03 UTC, hostadvantage commented on Tapawingo_backend.Tests/GET_Organisations/Organisations_Service_Tests.cs
> +            var organisation = _organisationsService.GetOrganisations();
Heb ik niet geschreven

2024-06-11 09:10 UTC, VincentVel approved these changes
correct

2024-06-11 09:11 UTC, VincentVel approved these changes
correct

2024-06-11 09:14 UTC, luuk-royal submitted a review, later dismissed

2024-06-11 09:23 UTC, hostadvantage commented on Tapawingo_backend.Tests/POST_Teams/Teams_Repository_Tests.cs
> +        //We don't need this test anymore because we're checking all misstakes in the service...
Nu verwijdert

2024-06-11 09:29 UTC, merged