Post editions
luuk-royal/tapawingohike_backend pull request #18
Opened 2024-06-06 11:52 UTC by luuk-royal

2024-06-06 21:22 UTC, StefNieuwhuis requested changes

2024-06-06 21:22 UTC, StefNieuwhuis commented on Tapawingo_backend/Services/EditionsService.cs
> +                throw new ArgumentException("Organisation does not exist");
Het is beter om geen exceptions the throwen dit is een vrij dure operatie. IActionResults returnen is de betere manier van foutafhandeling

2024-06-06 21:22 UTC, StefNieuwhuis commented on Tapawingo_backend/Controllers/EditionsController.cs
> +            [HttpPost("organisations/{organisation_id}/events/{event_id}/editions")]
Naar mijn weten wilden we niet meer deze langere urls. Volgensmij was het idee dat dit api/events/[id]/editions zou moeten worden

2024-06-06 21:22 UTC, StefNieuwhuis commented on Tapawingo_backend/Controllers/EditionsController.cs
> +            catch (ArgumentException ex)
De Try Catch kan weg zodra er IActionResults worden teruggestuurd vanuit de service (Zie volgende comment)

2024-06-09 08:31 UTC, VincentVel approved these changes
Changes look good, testen gaan wel fout

2024-06-10 08:17 UTC, VincentVel approved these changes
testen gaan goed

2024-06-10 08:18 UTC, StefNieuwhuis approved these changes

2024-06-10 08:18 UTC, merged